// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: tables.proto

package pbgen

import (
	_ "github.com/yaoguangduan/reskeeper/resproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZooTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Zoos []*Zoo `protobuf:"bytes,1,rep,name=zoos,proto3" json:"zoos,omitempty"`
}

func (x *ZooTable) Reset() {
	*x = ZooTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tables_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZooTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZooTable) ProtoMessage() {}

func (x *ZooTable) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZooTable.ProtoReflect.Descriptor instead.
func (*ZooTable) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{0}
}

func (x *ZooTable) GetZoos() []*Zoo {
	if x != nil {
		return x.Zoos
	}
	return nil
}

type ManagerTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mgr []*Manager `protobuf:"bytes,1,rep,name=mgr,proto3" json:"mgr,omitempty"`
}

func (x *ManagerTable) Reset() {
	*x = ManagerTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tables_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagerTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerTable) ProtoMessage() {}

func (x *ManagerTable) ProtoReflect() protoreflect.Message {
	mi := &file_tables_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerTable.ProtoReflect.Descriptor instead.
func (*ManagerTable) Descriptor() ([]byte, []int) {
	return file_tables_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerTable) GetMgr() []*Manager {
	if x != nil {
		return x.Mgr
	}
	return nil
}

var File_tables_proto protoreflect.FileDescriptor

var file_tables_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x66, 0x0a, 0x08, 0x5a, 0x6f, 0x6f, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x18,
	0x0a, 0x04, 0x7a, 0x6f, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x5a,
	0x6f, 0x6f, 0x52, 0x04, 0x7a, 0x6f, 0x6f, 0x73, 0x3a, 0x40, 0xf2, 0xbb, 0x18, 0x3c, 0x0a, 0x21,
	0xe6, 0xb5, 0x8b, 0xe8, 0xaf, 0x95, 0xe6, 0xa0, 0xb7, 0xe4, 0xbe, 0x8b, 0x2e, 0x78, 0x6c, 0x73,
	0x78, 0x23, 0xe5, 0x8a, 0xa8, 0xe7, 0x89, 0xa9, 0xe5, 0x9b, 0xad, 0xe5, 0x88, 0x97, 0xe8, 0xa1,
	0xa8, 0x12, 0x08, 0x5a, 0x6f, 0x6f, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x04, 0x66, 0x75, 0x6c,
	0x6c, 0x1a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x22, 0x59, 0x0a, 0x0c, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x6d, 0x67,
	0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x52, 0x03, 0x6d, 0x67, 0x72, 0x3a, 0x2d, 0xf2, 0xbb, 0x18, 0x29, 0x0a, 0x21, 0xe6, 0xb5,
	0x8b, 0xe8, 0xaf, 0x95, 0xe6, 0xa0, 0xb7, 0xe4, 0xbe, 0x8b, 0x2e, 0x78, 0x6c, 0x73, 0x78, 0x23,
	0xe7, 0xae, 0xa1, 0xe7, 0x90, 0x86, 0xe5, 0x91, 0x98, 0xe5, 0x88, 0x97, 0xe8, 0xa1, 0xa8, 0x1a,
	0x04, 0x66, 0x75, 0x6c, 0x6c, 0x42, 0x26, 0xa2, 0xbb, 0x18, 0x18, 0x0a, 0x08, 0x2e, 0x2e, 0x2f,
	0x65, 0x78, 0x63, 0x65, 0x6c, 0x12, 0x07, 0x2e, 0x2e, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x03,
	0x00, 0x01, 0x02, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tables_proto_rawDescOnce sync.Once
	file_tables_proto_rawDescData = file_tables_proto_rawDesc
)

func file_tables_proto_rawDescGZIP() []byte {
	file_tables_proto_rawDescOnce.Do(func() {
		file_tables_proto_rawDescData = protoimpl.X.CompressGZIP(file_tables_proto_rawDescData)
	})
	return file_tables_proto_rawDescData
}

var file_tables_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tables_proto_goTypes = []any{
	(*ZooTable)(nil),     // 0: ZooTable
	(*ManagerTable)(nil), // 1: ManagerTable
	(*Zoo)(nil),          // 2: Zoo
	(*Manager)(nil),      // 3: Manager
}
var file_tables_proto_depIdxs = []int32{
	2, // 0: ZooTable.zoos:type_name -> Zoo
	3, // 1: ManagerTable.mgr:type_name -> Manager
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tables_proto_init() }
func file_tables_proto_init() {
	if File_tables_proto != nil {
		return
	}
	file_demo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_tables_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ZooTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tables_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ManagerTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tables_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tables_proto_goTypes,
		DependencyIndexes: file_tables_proto_depIdxs,
		MessageInfos:      file_tables_proto_msgTypes,
	}.Build()
	File_tables_proto = out.File
	file_tables_proto_rawDesc = nil
	file_tables_proto_goTypes = nil
	file_tables_proto_depIdxs = nil
}
